name: Deploy HTML Template to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@YOUR_EC2_PUBLIC_IP << 'EOF'
          # Update system and install required dependencies
          sudo apt update -y
          sudo apt install -y docker.io git
          sudo systemctl start docker
          sudo systemctl enable docker

          # Remove old files and pull new code
          sudo rm -rf /var/www/html/*
          git clone https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPOSITORY.git /var/www/html

          # Remove existing container if running
          sudo docker stop html-container || true
          sudo docker rm html-container || true

          # Run a new Docker container with Nginx serving the HTML template
          sudo docker run -d --name html-container -p 80:80 -v /var/www/html:/usr/share/nginx/html nginx
          EOF
