Task: Deploying an HTML Web Template on AWS using GitHub Actions and Docker
Objective:
You are required to download an HTML web template from the internet, set up a GitHub Actions workflow, and automate the deployment of this template on an AWS EC2 instance using Docker. The deployed website should be publicly accessible via the Public DNS of the EC2 instance on a specified port.
Instructions:
1.	Download an HTML Web Template:
o	Search for and download a free HTML web template from any reliable
o	Extract the files and organize them properly inside a repository.
2.	Set Up GitHub Actions Workflow:
o	Inside the root of your repository, create a hidden directory named .github/workflows (as per industry standards).
o	Inside this folder, create a file called deploy.yaml that defines the CI/CD pipeline for deploying the HTML template on AWS.
3.	Define Deployment Steps in deploy.yaml:
Your workflow should include the following automated steps:
o	Trigger on Push Events:
	The workflow should be triggered whenever code is pushed to the main branch.
o	Spin Up an AWS EC2 Instance:
	Use an Ubuntu-based EC2 instance to host the application.
	Ensure that IAM roles and security groups are properly configured to allow incoming traffic.
o	Install Required Dependencies on EC2:
	Install Docker and ensure it is running.
